# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# https://github.com/goreleaser/goreleaser/pull/4391
version: 2

report_sizes: true

builds:
  # https://goreleaser.com/customization/build/
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
    targets:
      # First class ports: https://go.dev/wiki/PortingPolicy#first-class-ports
      - go_118_first_class
      - freebsd_arm64
      - freebsd_amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  # https://goreleaser.com/customization/archive/
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"

release:
  # https://goreleaser.com/customization/release/
  target_commitish: "{{ .Commit }}"
  mode: replace
  header: |
    ### [README.md](https://github.com/grishy/gopkgview#readme) - For information on how to install and use
  footer: |
    Your PRs and issues are welcome! Thanks 😉
  disable: false
  skip_upload: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Improvements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 999
